[package]
name = "annoyify"
version = "0.2.0"
authors = ["Tronje Krabbe <hi@tron.je>"]
edition = "2021"
license = "0BSD"
description = "AnNoYiFy TeXt To LoOk LiKe ThIs"

[dependencies]
clap = "2.32"
rand = "0.6"
